kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: app-stack
nodes:
  - role: control-plane
  - role: worker
  - role: worker
networking:
  disableDefaultCNI: false
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
